### ISSUE TITLE
Look what to do in the exercise

### ISSUE THREAD

**Issue by u1979272** [Lucem-Joc-en-Grup/Per-Aspera-Ad-Lucem#1]
Part 1 of the project in PDf: create a repository, Wiki, invite the professor, etc.

**Comment by TadiwanasheZvidzaRodney** [comment]
hello. i'd love to contribute to the available issue but it's not quite clear what i'm supposed to do. please care to lead me

**Comment by u1979272** [comment]
hi, sorry for the confusion, this issue is a part of the uni project that i have to do alone. it is only public so i can create wikis. thanks for your interest anyway!

**Comment by TadiwanasheZvidzaRodney** [comment]
> hi, sorry for the confusion, this issue is a part of the uni project that i have to do alone. it is only public so i can create wikis. thanks for your interest anyway!

all right. thank you
